import React from 'react';
import { THREAT_MATRIX } from '../data';
import { ShieldCheck, ShieldAlert, Check, AlertTriangle } from 'lucide-react';

export const ThreatModelView: React.FC = () => {
  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-semibold text-slate-900 tracking-tight">
          Censorship Evasion & DPI Threat Model Matrix
        </h2>
        <p className="text-sm text-slate-600 mt-1">
          Cryptographic analysis and real-world operational evaluation of transports against deep packet inspection, active probing, and carrier firewalls.
        </p>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-50 border-b border-slate-200 text-slate-700 uppercase font-semibold tracking-wider">
              <tr>
                <th className="p-3.5">Threat Scenario</th>
                <th className="p-3.5">Status</th>
                <th className="p-3.5">Mitigation Mechanism</th>
                <th className="p-3.5">Operational Limitations</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {THREAT_MATRIX.map((threat, idx) => (
                <tr key={idx} className="hover:bg-slate-50/70 transition-colors">
                  <td className="p-3.5 font-medium text-slate-900 max-w-xs">{threat.threat}</td>
                  <td className="p-3.5 whitespace-nowrap">
                    {threat.mitigated === true ? (
                      <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-emerald-50 text-emerald-700 border border-emerald-200">
                        <Check className="w-3 h-3 mr-1" />
                        Mitigated
                      </span>
                    ) : (
                      <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-amber-50 text-amber-700 border border-amber-200">
                        <AlertTriangle className="w-3 h-3 mr-1" />
                        Partial / Failover
                      </span>
                    )}
                  </td>
                  <td className="p-3.5 text-slate-700 max-w-md">{threat.mitigationMechanism}</td>
                  <td className="p-3.5 text-slate-500 max-w-xs">{threat.limitations}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="p-4 bg-white rounded-xl border border-slate-200 shadow-xs">
          <div className="flex items-center space-x-2 text-slate-900 font-semibold text-sm mb-1">
            <ShieldCheck className="w-4 h-4 text-emerald-600" />
            <span>uTLS Google Chrome Fingerprinting</span>
          </div>
          <p className="text-xs text-slate-600 leading-relaxed">
            By pinning <code className="font-mono bg-slate-100 px-1 py-0.5 rounded">fp=chrome</code> in client VLESS profiles, the TLS ClientHello packet generated by HAPP on Android mirrors Google Chrome down to cipher suites, extensions, elliptic curves, and ALPN order, neutralizing JA3/JA4 fingerprint filters.
          </p>
        </div>

        <div className="p-4 bg-white rounded-xl border border-slate-200 shadow-xs">
          <div className="flex items-center space-x-2 text-slate-900 font-semibold text-sm mb-1">
            <ShieldAlert className="w-4 h-4 text-purple-600" />
            <span>Active Prober Defense (Reality Fallbacks)</span>
          </div>
          <p className="text-xs text-slate-600 leading-relaxed">
            When state firewall probers scan the VPS port 443 with arbitrary TLS handshakes, Xray forwards the connection directly to <code className="font-mono bg-slate-100 px-1 py-0.5 rounded">www.microsoft.com:443</code>. The scanner receives 100% genuine Microsoft TLS certificates, defeating scanner-based blocklists.
          </p>
        </div>
      </div>
    </div>
  );
};
