import { ProxyProfile, DiagnosticItem, ThreatItem } from './types';

export const PROFILES: ProxyProfile[] = [
  {
    id: 'profile-a',
    code: 'A',
    name: 'Direct VLESS-Reality (Vision)',
    protocol: 'VLESS',
    transport: 'TCP + XTLS-Reality',
    security: 'Reality (X25519) + uTLS Chrome',
    port: 443,
    targetHost: 'Linux VPS (Public IPv4)',
    stealthRating: 'Very High',
    natTraversal: 'Direct (Requires Public IP)',
    bestFor: 'Primary high-speed uncapped streaming, lowest latency, zero proxy overhead.',
    latencyExpectation: 'Lowest (Direct to VPS)',
    details: 'Imitates authentic TLS 1.3 ClientHello to www.microsoft.com. Unauthorized probes are transparently forwarded to authentic Microsoft web servers.',
  },
  {
    id: 'profile-b1',
    code: 'B1',
    name: 'Cloudflare Tunnel WebSocket',
    protocol: 'VLESS (decryption: none)',
    transport: 'WebSocket + TLS',
    security: 'Cloudflare Edge TLS 1.3',
    port: 443,
    targetHost: 'Windows 11 / Orange Pi (Behind NAT)',
    stealthRating: 'High',
    natTraversal: 'Cloudflare Tunnel (No Port Forwarding)',
    bestFor: 'Residential hosts behind Carrier-Grade NAT (CGNAT) without public IP or open ports.',
    latencyExpectation: 'Low-Medium (CDN Anycast Hop)',
    details: 'Traffic exits over an outbound QUIC tunnel to Cloudflare Edge. Your home IP address and ports remain completely hidden.',
  },
  {
    id: 'profile-b2',
    code: 'B2',
    name: 'Cloudflare Tunnel XHTTP (SplitHTTP)',
    protocol: 'VLESS (decryption: none)',
    transport: 'XHTTP (packet-up) + TLS',
    security: 'Cloudflare Edge TLS 1.3',
    port: 443,
    targetHost: 'Windows 11 / Orange Pi (Behind NAT)',
    stealthRating: 'Extreme',
    natTraversal: 'Cloudflare Tunnel (No Port Forwarding)',
    bestFor: 'Bypassing strict DPI firewalls that inspect or drop WebSocket Upgrade headers.',
    latencyExpectation: 'Low-Medium (No stream buffering)',
    details: 'Uses pure HTTP POST streaming channels instead of WebSocket framing, completely eliminating WebSocket protocol signatures.',
  },
  {
    id: 'profile-c',
    code: 'C',
    name: 'ZeroTier Emergency Mesh',
    protocol: 'VLESS (Unencrypted L7)',
    transport: 'TCP over ZeroTier L3',
    security: 'Salsa20-Poly1305 (ZeroTier Layer)',
    port: 10808,
    targetHost: 'Any Host running ZeroTier',
    stealthRating: 'Medium',
    natTraversal: 'ZeroTier L3 Mesh',
    bestFor: 'Out-of-band emergency recovery when Cloudflare Anycast or public IPs are unreachable.',
    latencyExpectation: 'Direct P2P or Relay',
    details: 'Traverses NAT through ZeroTier STUN relays and direct UDP hole-punching. Independent of public DNS and web domains.',
  },
];

export const DIAGNOSTICS: DiagnosticItem[] = [
  {
    id: 'cf-1000',
    category: 'Cloudflare',
    symptom: 'Cloudflare Error 1000: DNS points to prohibited IP',
    possibleCauses: [
      'DNS record points to server local loopback 127.0.0.1 directly instead of being routed via Cloudflare Tunnel CNAME',
      'The domain is not assigned to the active Cloudflare Tunnel connector token',
    ],
    verificationCommand: 'cloudflared tunnel info <TUNNEL_NAME_OR_ID>',
    remedy: 'In Cloudflare Zero Trust dashboard > Networks > Tunnels > Public Hostname, configure tunnel.yourdomain.com pointing to Service: HTTP -> localhost:10809 (or 10808).',
  },
  {
    id: 'ws-100-sec',
    category: 'Mobile / Cellular',
    symptom: 'HAPP Android client disconnects exactly every 100 seconds of idle time',
    possibleCauses: [
      'Cloudflare Free Tier strictly enforces a 100-second idle connection timeout on WebSocket streams',
    ],
    verificationCommand: 'grep -i "timeout" /var/log/xray/access.log',
    remedy: 'In HAPP Android client settings, enable "Keep-Alive Ping" (or Mux heartbeat interval set to 30-50 seconds) to ensure periodic packet transmission.',
  },
  {
    id: 'handshake-timeout',
    category: 'Mobile / Cellular',
    symptom: 'Handshake timeout or "connection refused" during LTE to Wi-Fi handoff',
    possibleCauses: [
      'Mobile carrier gateway change tears down active TCP socket before client uTLS finishes re-negotiation',
      'Local carrier DNS server blocks unencrypted DNS queries',
    ],
    verificationCommand: 'ping -c 3 tunnel.yourdomain.com',
    remedy: 'In HAPP, enable DNS-over-HTTPS (DoH) with URL: https://1.1.1.1/dns-query. Set reconnect retries to automatic.',
  },
  {
    id: 'opi-oom',
    category: 'Orange Pi / Hardware',
    symptom: 'Xray service terminated silently (OOM Killer) on 1GB / 512MB RAM board',
    possibleCauses: [
      'Go runtime garbage collection memory ballooning under high concurrent connection loads',
      'System log files overflowing flash memory',
    ],
    verificationCommand: 'dmesg | grep -i oom',
    remedy: 'Run server/orangepi/tuning.sh to enable ZRAM with LZ4 compression. Ensure GOMEMLIMIT=256MiB is active in /etc/systemd/system/xray.service.',
  },
  {
    id: 'reality-fallback',
    category: 'Xray Core',
    symptom: 'Direct VPS connection returns HTTP 400 Bad Request or standard Microsoft page',
    possibleCauses: [
      'Client X25519 private/public key mismatch or incorrect Short ID',
      'Server port 443 fallback target domain does not support TLS 1.3 / H2',
    ],
    verificationCommand: 'xray -test -config /usr/local/etc/xray/config.json',
    remedy: 'Verify that client public key matches server private key. Test target fallback server support using curl -Iv https://www.microsoft.com.',
  },
];

export const THREAT_MATRIX: ThreatItem[] = [
  {
    threat: 'SNI Inspection & Blocking',
    mitigated: true,
    mitigationMechanism: 'Profile A uses Reality to spoof legitimate Microsoft SNI. Profile B1/B2 uses authentic Cloudflare Edge TLS certificates.',
    limitations: 'If the specific Cloudflare domain or Microsoft SNI is strictly blacklisted in DNS/SNI filters.',
  },
  {
    threat: 'Active Probing / Scanner Attacks',
    mitigated: true,
    mitigationMechanism: 'Xray forwards unauthorized probes on port 443 to the authentic Microsoft server. Cloudflare drops unauthorized paths with HTTP 404.',
    limitations: 'Fallback destination must maintain identical TLS 1.3 cipher suite order.',
  },
  {
    threat: 'TLS Fingerprinting (JA3 / JA4 / uTLS)',
    mitigated: true,
    mitigationMechanism: 'Client uTLS implements Chrome fingerprinting (fp=chrome), aligning cipher order, ALPN, and elliptic curves with Google Chrome on Android.',
    limitations: 'Requires client app support (HAPP supports uTLS by default).',
  },
  {
    threat: 'Cloudflare IP Subnet Blacklisting',
    mitigated: 'Partial',
    mitigationMechanism: 'Multi-profile failover instantly switches client to Direct VPS (Profile A) or ZeroTier Mesh (Profile C).',
    limitations: 'Profile B alone will fail if all Cloudflare Anycast IP ranges are completely severed by carrier.',
  },
  {
    threat: 'DPI WebSocket Framing Heuristics',
    mitigated: true,
    mitigationMechanism: 'Profile B2 replaces WebSocket framing with pure XHTTP POST streams (SplitHTTP).',
    limitations: 'Carrier DPI inspecting sustained high-volume bandwidth over hours.',
  },
];
